### ISSUE TITLE
Connecting database via ssh

### ISSUE THREAD

**Issue by balintgaspar** [ixkaito/wocker#13]
Hi!
I'm trying to connect to wocker running container's db via Sequel Pro. SSH is succeeded but connection is refused to connect

How can I connect to running container's db? ports? ip?

I tried:

docker inspect --format='{{.NetworkSettings.IPAddress}}' "truevgd"wich gives me an IP address but I can't connect...

Best: Balint.

**Comment by ixkaito** [comment]
Hello!
Thanks for using Wocker!

Could you please copy this issue to https://github.com/wckr/wocker/issues?
I'll reply you there.

**Comment by balintgaspar** [comment]
Done! :) Thank you for your work:)

**Comment by ixkaito** [comment]
Move to: https://github.com/wckr/wocker/issues/15.
