### ISSUE TITLE
SSH-2.0-OpenSSH_6.4 Protocol mismatch

### ISSUE THREAD

**Issue by jastuccio** [ixkaito/wocker#18]
When I surf to 127.0.0.1:2022 the browser reports the error  `SSH-2.0-OpenSSH_6.4 Protocol mismatch`  How do I correct this?

**Comment by ixkaito** [comment]
Could you please copy this to https://github.com/wckr/wocker/issues?

**Comment by jastuccio** [comment]
done. thank you
