### ISSUE TITLE
Moving Wocker to a new computer

### ISSUE THREAD

**Issue by joeynimu** [ixkaito/wocker#21]
Hi,

I am not sure if this is an issue really more than just a question.

I want to switch machines for my current one is a bit old and it is becoming slow. So the question is, how do I move all my wocker projects from my old mac to my new one ensuring that everything will run seamlessly on the new machine?
I presume first thing first is that I have to install wocker on the new machine which I have. Do  I have to copy the whole of the data directory and manually export the databases or is there another simpler way?

Many Thanks for Wocker. It has really eased by WP development process.

**Comment by ixkaito** [comment]
Moved to https://github.com/wckr/wocker/issues/67.
