### ISSUE TITLE
Ubuntu needs nfs-kernel-server installed

### ISSUE THREAD

**Issue by m-e-h** [ixkaito/wocker#4]
Just wanted to point this out in case anyone else got this message on Linux:

    It appears your machine doesn't support NFS, or there is not an adapter to enable NFS on this machine for Vagrant.

They'll need to:

    apt-get install nfs-kernel-server

Here's the issue the original issue thread https://github.com/mitchellh/vagrant/issues/1534/#issuecomment-34242441

**Comment by ixkaito** [comment]
Thanks!

Could you please copy this issue to https://github.com/wckr/wocker/issues.
I'll deal with it later.

**Comment by m-e-h** [comment]
Will do. Sorry, didn't realize there was another repo.
