### ISSUE TITLE
Wordpress Directory Not Renamed On 'vagrant halt'

### ISSUE THREAD

**Issue by jcpeden** [ixkaito/wocker#8]
When I halt my vagrant box, the wordpress directory in the data dir is not renamed to match the wocker container.

This means the wocker container is effectively orphaned and must be manually renamed to match the container ID before I spin it up again.

Am I doing something wrong?

**Comment by ixkaito** [comment]
You're right, so I've written about this in the documentation. http://wckr.github.io/#h2-4
However, I'm planning to fix this issue in later version.

**Comment by ixkaito** [comment]
Fixed this in v0.3.0.
https://github.com/wckr/wocker
